openapi: 3.0.0
info:
  version: 0.5.0
  title: ASR and TTS API and schema definitions
  description: >-
    Contributor developing models under ASR, TSS task, should implement following schema and API contract for their end point. This will enable ULCA to make inference callback for benchmark and try me functionalities.
  contact:
    name: ekstep foundation
    email: contact@ekstep.org

paths: {}

components:
  securitySchemes:
    authToken:
      type: apiKey
      description: token issued by authenticating the user
      name: auth-token
      in: header

  schemas:
    RecognitionAudio:
      type: object
      required:
        - audio_content|audio_uri|fileId
        - language
      properties:
        oneOf:
          audio_content:
            type: string
            format: byte
            example: "byte64 encoded string"
          audio_uri:
            type: string
            description: "path on gcp/s3 bucket or https url"
            example: "gs://bucket/audio.wav"
          fileId:
            type: string
            description: fileId should be same as returned in the response of file-upload
        language:
          $ref: "https://raw.githubusercontent.com/project-anuvaad/ULCA/develop/common-schemas.yml#/components/schemas/Language"
        transcript_format:
          $ref: "#/components/schemas/TranscriptionFormat"
        audio_format:
          $ref: "https://raw.githubusercontent.com/project-anuvaad/ULCA/develop/common-schemas.yml#/components/schemas/AudioFormat"
        channel:
          $ref: "https://raw.githubusercontent.com/project-anuvaad/ULCA/develop/common-schemas.yml#/components/schemas/AudioChannel"
        samplingRate:
          $ref: "https://raw.githubusercontent.com/project-anuvaad/ULCA/develop/common-schemas.yml#/components/schemas/AudioSampleRate"
        bitsPerSample:
          $ref: "https://raw.githubusercontent.com/project-anuvaad/ULCA/develop/common-schemas.yml#/components/schemas/AudioBitsPerSample"
        numberOfSpeakers:
          $ref: "https://raw.githubusercontent.com/project-anuvaad/ULCA/develop/common-schemas.yml#/components/schemas/NumberOfSpeakers"
        punctuation:
          type: boolean
          example: true

    TranscriptionFormat:
      type: object
      properties:
        value:
          type: string
          description: format of ASR output
          enum:
            - srt
            - transcript
            - alternatives

    SpeechRecognitionResult:
      type: object
      required:
        - status
      properties:
        oneOf:
          transcript:
            type: string
            example: "This is text"
          alternatives:
            $ref: "#/components/schemas/Alternatives"
          srt:
            type: string
            example: "--> This is srt text"
        status:
          $ref: "#/components/schemas/RecognitionStatus"
        channelTag:
          type: integer
          description: "For multi-channel audio, this is the channel number corresponding to the recognized result for the audio from that channel. For audioChannelCount = N, its output values can range from '1' to 'N'"
        languageCode:
          type: string
          description: "This language code was detected to have the most likelihood of being spoken in the audio"

    RecognitionStatus:
      type: object
      properties:
        value:
          type: string
          description: "status of ASR response"
          enum:
            - success
            - no-match
            - initial-silence-timeout
            - babble-timeout
            - error

    Alternative:
      type: object
      properties:
        word:
          type: string
          description: word detected
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time

    Alternatives:
      type: array
      items:
        $ref: "#/components/schemas/Alternative"
        minItems: 1
