openapi: 3.0.0
info:
  title: Unified Language Contribution API (ULCA) documentation
  description: The document defines the common schema object used across all available APIs 
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 0.1.0

paths: {}

components:
  schemas:
    Language:
      type: object
      properties:
        value:
          type: string
          description: Indic language code, iso-639-1, iso 639-2
          enum:
          - en
          - hi
          - mr
          - ta
          - te
          - kn
          - gu
          - pa
          - bn
          - ml
          - as
          - brx
          - doi
          - ks
          - kok
          - mai
          - mni
          - ne
          - or
          - sd
          - si
          - ur
          - sat
          - lus
          - njz
          - pnr
          - kha
          - grt
          - sa
        name:
          type: string
          description: human name of language code

    LanguagePair:
      type: object
      description: language pair, make targetLanguage null to reuse the object to indicate single language
      required:
        - sourceLanguage
      properties:
        sourceLanguage:
          $ref: '#/components/schemas/Language'
        targetLanguage:
          $ref: '#/components/schemas/Language'
    
    LanguagePairs:
        type: array
        items:
          $ref: '#/components/schemas/LanguagePair'
          minItems: 1
    
    Domain:
        type: object
        properties:
          value:
            type: array
            items:
              type: string
              enum:
              - general
              - news
              - education
              - legal
              - government-press-release
              - healthcare
              - movies
              - subtitles
              - sports
    
    License:
      type: object
      properties:
        value:
          type: string
          enum:
          - cc-by-4.0
          - mit
          - gpl-3.0
          - bsd-3-clause
          - cc-by-nd-2.0
          
    Contributor:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 50
          minLength: 5
          type: string
          description: human name of the contributor
        oauthId:
          $ref: '#/components/schemas/OAuthIdentity'
        aboutMe:
          type: string
          description: describing the contributor
    
    OAuthIdentity:
      type: object
      properties:
        identifier:
          type: string
          description: system identification for the contributor
          format: uuidv4
        oauthId:
          type: string
          description: popular social network identifier, typically identifier returned after auth
        provider:
          type: string
          description: user authentication provider
          enum:
          - custom
          - github
          - facebook
          - instagram
          - google
          - yahoo
    
    Source:
      type: object
      properties:
        value:
          type: array
          description: user defined sources
          items:
            type: string
    
    CollectionMethod:
      type: object
      properties:
        value:
          type: array
          description: various collection methods user have used to create the dataset
          items:
            type: string
            enum:
            - web-scrapping
            - manual-human-translated
            - algorithm-auto-aligned
            - algorithm-back-translated
            - phone-recorded-audio
            - crowd-sourced-audio

    DataPoint:
      required:
      - label
      - value
      type: object
      properties:
        label:
          type: string
          description: string value to show
        value:
          type: number
          description: numeric value of the data point
        internalLabel:
          type: string
          description: internal representation of the label

    ImageFormat:
      type: object
      properties:
        value:
          type: string
          description: image format description
          enum:
          - jpeg
          - bmp
          - png
          - tiff
    
    ImageTextType:
      type: object
      properties:
        value:
          type: string
          description: textual data present in the image file
          enum:
          - scene-text
          - typewriter-typed-text
          - computer-typed-text
          - handwritten-text
    
    ImageDPI:
      type: object
      properties:
        value:
          type: string
          description: allowed dpi
          enum:
          - 300_dpi
          - 72_dpi
    
    AudioFormat:
      type: object
      properties:
        value:
          type: string
          description: audio format description
          enum:
          - wav
          - pcm
          - mp3
    
    AudioChannel:
      type: object
      properties:
        value:
          type: string
          description: number of channel in the audio
          enum:
          - mono
          - stero
    
    AudioSampleRate:
      type: object
      properties:
        value:
          type: string
          description: sample rate of the audio file
          enum:
          - 44khz
          - 22khz
          - 8khz
    
    AudioBitsPerSample:
      type: object
      properties:
        value:
          type: string
          description: number of bits per sample
          enum:
          - sixteen
          - eight
          
    NumberOfSpeakers:
      type: object
      properties:
        value:
          type: number
          description: number of speakers in the recorded audio file
          minimum: 1
    
    NumberOfHoursPerGenders:
      type: array
      items:
        $ref: '#/components/schemas/NumberOfHoursPerGender'
        minItems: 1
    
    NumberOfHoursPerGender:
      type: object
      properties:
        value:
          type: number
          description: number of hours per gender
          minimum: 1
        gender:
          type: string
          description: gender description
          enum:
            - male
            - female
            - others
