openapi: 3.0.0
info:
  title: Unified Language Contribution API (ULCA) documentation
  description: The document defines the common schema object used across all available APIs 
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 0.1.0

paths: {}

components:
  schemas:
    LanguagePair:
      type: object
      description: language pair, make targetLanguage null to reuse the object to indicate single language
      required:
        - sourceLanguage
      properties:
        type:
          type: string
          enum:
          - PARAMS
        sourceLanguage:
          $ref: '#/components/schemas/Language'
        targetLanguage:
          $ref: '#/components/schemas/Language'
    
    Language:
      type: object
      properties:
        type:
          type: string
          enum:
          - PARAMS
        value:
          type: string
          description: Indic language code, iso-639-1, iso 639-2
          enum:
          - en
          - hi
          - mr
          - ta
          - te
          - kn
          - gu
          - pa
          - bn
          - ml
          - as
          - brx
          - doi
          - ks
          - kok
          - mai
          - mni
          - ne
          - or
          - sd
          - si
          - ur
          - sat
          - lus
          - njz
          - pnr
          - kha
          - grt
          - sa
        name:
          type: string
          description: human name of language code

    LanguagePairs:
        type: array
        items:
          $ref: '#/components/schemas/LanguagePair'
          minItems: 1
    
    Domain:
        type: object
        properties:
          value:
            type: array
            items:
              type: string
              enum:
              - general
              - news
              - education
              - legal
              - government-press-release
              - healthcare
              - movies
              - subtitles
              - sports
    
    License:
      type: object
      properties:
        value:
          type: string
          enum:
          - cc-by-4.0
          - mit
          - gpl-3.0
          - bsd-3-clause
          - cc-by-nd-2.0
          
    Contributor:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 50
          minLength: 5
          type: string
          description: human name of the contributor
        oauthId:
          $ref: '#/components/schemas/OAuthIdentity'
        aboutMe:
          type: string
          description: describing the contributor
    
    OAuthIdentity:
      type: object
      properties:
        identifier:
          type: string
          description: system identification for the contributor
          format: uuidv4
        oauthId:
          type: string
          description: popular social network identifier, typically identifier returned after auth
        provider:
          type: string
          description: user authentication provider
          enum:
          - custom
          - github
          - facebook
          - instagram
          - google
          - yahoo
    