openapi: 3.0.0
info:
  title: Unified Language Contribution API (ULCA) documentation
  description: 'Models for process tracker'
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 0.7.0
components:
  schemas:
    processTracker:
      type: object
      description: Process Tracker entity
      properties:
        userId:
          type: string
          description: Id of the user
          required: true
        datasetId:
          type: string
          description: Unique identifier of the dataset
        serviceRequestNumber:
          type: string
          description: Unique identifier of the service request
          required: true
        serviceRequestType:
          type: string
          description: Type of the service request
          enum:
            - datatset
            - model
            - benchmark
          required: true
        serviceRequestAction:
          type: string
          description: Action being performed on the service request type
          enum:
            - submit
            - search
            - abort
            - delete
            - update
          required: true
        status:
          type: string
          description: Status of the process
          enum:
            - notstarted
            - inprogress
            - successful
            - failed
          required: true
        details:
          type: object
          description: Details of the curren status of the process
          required: true
        startTime:
          type: number
          description: ISO timestamp of the instance of the start of process
          format: datetime
          required: true
        endTime:
          type: number
          description: ISO timestamp of the instance of the end of process
          format: datetime
        lastModified:
          type: number
          description: ISO timestamp of the instance of the end of process
          format: datetime
        error:
          type: object
          description: Error details if any
          $ref: '#/error'
          
          
    taskTracker:
      type: object
      description: Task Tracker entity
      properties:
        serviceRequestNumber:
          type: string
          description: Unique identifier of the service request
          required: true
        tool:
          type: string
          description: Tool updating this data
          enum:
            - download
            - ingest
            - validate
            - publish
            - search
            - delete
          required: true
        status:
          type: string
          description: Status of the task
          enum:
            - notstarted
            - inprogress
            - successful
            - failed
          required: true
        details:
          type: object
          description: Details of the current status of the task
          required: true
        startTime:
          type: number
          description: ISO timestamp of the instance of the start of process
          format: datetime
          required: true
        endTime:
          type: number
          description: ISO timestamp of the instance of the end of process
          format: datetime
        lastModified:
          type: number
          description: ISO timestamp of the instance of the end of process
          format: datetime
        error:
          type: object
          description: Error details if any
          $ref: '#/error'

          
          
          
    detailsSubmit:
        type: object
        description: Task Tracker entity
        properties:
          currentRecordIndex:
            type: number
            description: Index of the record under processing
            required: true
          processedCount:
            type: object
            description: total no of records tied to be processed as part of the current process
            required: true
            $ref: '#/processedCount'
          timeStamp:
            type: number
            description: ISO timestamp of the instance of the start of process
            format: datetime
            required: true
            
            
    detailsSearch:
        type: object
        description: Task Tracker entity
        properties:
          count:
            type: number
            description: Count of records retrieved
            required: true
          dataset:
            type: number
            description: link to the retrieved dataset
            required: true
          timeStamp:
            type: number
            description: ISO timestamp of the instance of the start of process
            format: datetime
            required: true
            
            
    detailsDelete:
        type: object
        description: Task Tracker entity
        properties:
          count:
            type: number
            description: Count of records deleted
            required: true
          timeStamp:
            type: number
            description: ISO timestamp of the instance of the start of process
            format: datetime
            required: true
            
    processedCount:
        type: object
        description: Task Tracker entity
        properties:
          type:
            type: string
            description: 
            enum:
              - successful
              - failed
            required: true
          typeDetails:
            type: string
            description: 
            enum:
              - duplicate
              - invalid
              - internal-error
          count:
            type: number
            description: Count of the records falling into this category
            required: true

    error:
        type: object
        description: Task Tracker entity
        properties:
          code:
            type: string
            description: Code of the error
            required: true
          message:
            type: string
            description: Description of the error
            required: true
          cause:
            type: object
            description: Additional details related to the cause of the error
          report:
            type: string
            description: Link to the error report file
